export const cvAnalysisJsonSchema = {
  type: "object",
  additionalProperties: false,
  properties: {
    matchScore: {
      type: "integer",
      minimum: 0,
      maximum: 100,
      description: "Overall CV-to-job fit score from 0 to 100.",
    },
    atsScore: {
      type: "integer",
      minimum: 0,
      maximum: 100,
      description: "Estimated applicant tracking system compatibility score from 0 to 100.",
    },
    keywordCoverage: {
      type: "integer",
      minimum: 0,
      maximum: 100,
      description: "Estimated percentage of important job keywords represented in the CV.",
    },
    missingKeywords: {
      type: "array",
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Important job keywords or concepts missing from the CV.",
    },
    strengths: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Evidence-backed strengths in the CV for the target job.",
    },
    weaknesses: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Evidence-backed risks or gaps for the target job.",
    },
    improvements: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Actionable CV edits that preserve truthfulness.",
    },
    rewrittenSummary: {
      type: "string",
      minLength: 1,
      maxLength: 2000,
      description: "A concise rewritten professional summary tailored to the job.",
    },
    mainReasonsForScore: {
      type: "array",
      minItems: 1,
      maxItems: 8,
      items: { type: "string", minLength: 1 },
      description:
        "The main evidence-based reasons behind the match score, including penalties for missing required experience.",
    },
    confidenceLevel: {
      type: "string",
      enum: ["low", "medium", "high"],
      description:
        "Confidence in the analysis based on CV text quality and amount of direct evidence.",
    },
    recruiterVerdict: {
      type: "string",
      minLength: 1,
      maxLength: 1200,
      description:
        "A brutally honest recruiter-style verdict about whether the candidate is likely to be shortlisted.",
    },
    rejectionRisks: {
      type: "array",
      minItems: 3,
      maxItems: 3,
      items: { type: "string", minLength: 1 },
      description: "The top three evidence-based risks that could cause rejection.",
    },
    fastestFixes: {
      type: "array",
      minItems: 3,
      maxItems: 3,
      items: { type: "string", minLength: 1 },
      description:
        "The top three fastest CV edits that would improve job fit without inventing experience.",
    },
    strongPoints: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Compatibility alias for strengths. Keep semantically equivalent to strengths.",
    },
    weakPoints: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Compatibility alias for weaknesses. Keep semantically equivalent to weaknesses.",
    },
    suggestedImprovements: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Compatibility alias for improvements. Keep semantically equivalent to improvements.",
    },
    coverLetter: {
      type: "string",
      minLength: 1,
      maxLength: 8000,
      description: "A concise draft cover letter tailored to the job.",
    },
    interviewQuestions: {
      type: "array",
      minItems: 1,
      maxItems: 20,
      items: { type: "string", minLength: 1 },
      description: "Role-specific interview preparation questions.",
    },
  },
  required: [
    "matchScore",
    "atsScore",
    "keywordCoverage",
    "missingKeywords",
    "strengths",
    "weaknesses",
    "improvements",
    "rewrittenSummary",
    "mainReasonsForScore",
    "confidenceLevel",
    "recruiterVerdict",
    "rejectionRisks",
    "fastestFixes",
    "strongPoints",
    "weakPoints",
    "suggestedImprovements",
    "coverLetter",
    "interviewQuestions",
  ],
} as const;
